### ISSUE TITLE
Error with the code "data = spio.loadmat(filename, struct_as_record=False, squeeze_me=True)"

### ISSUE THREAD

**Issue by robertodaza** [rafabs97/headpose_final#4] opened 2020-11-04 22:06 UTC
Hello:

I have a problem with the file "head-detector.mat"  and the code `spio.loadmat("models/head-detector.mat", struct_as_record=False, squeeze_me=True)`. I always get the next  error  `ValueError: Unknown mat file type, version 57, 48`. 
How can I fix this problem?

Thank you very much in advance.

Regards.

**Comment by rafabs97** [comment] 2020-11-04 22:28
In which file does that line appear? I am not able to find that line in my code.

**Comment by robertodaza** [comment] 2020-11-04 23:27
> In which file does that line appear? I am not able to find that line in my code.

In the file "loadmat_stackoverflow.py", line 59. The code is:

```
# -*- coding: utf-8 -*-

"""
This file contains a function used to load .mat files into a Python program, maintaining the structure of nested
dictionaries. The code was obtained from https://stackoverflow.com/a/8832212, April 11, 2019, and is presented as-is,
with the original comments.
"""

import scipy.io as spio
import numpy as np

def loadmat(filename):
    '''
    this function should be called instead of direct spio.loadmat
    as it cures the problem of not properly recovering python dictionaries
    from mat files. It calls the function check keys to cure all entries
    which are still mat-objects
    '''
    def _check_keys(d):
        '''
        checks if entries in dictionary are mat-objects. If yes
        todict is called to change them to nested dictionaries
        '''
        for key in d:
            if isinstance(d[key], spio.matlab.mio5_params.mat_struct):
                d[key] = _todict(d[key])
        return d

    def _todict(matobj):
        '''
        A recursive function which constructs from matobjects nested dictionaries
        '''
        d = {}
        for strg in matobj._fieldnames:
            elem = matobj.__dict__[strg]
            if isinstance(elem, spio.matlab.mio5_params.mat_struct):
                d[strg] = _todict(elem)
            elif isinstance(elem, np.ndarray):
                d[strg] = _tolist(elem)
            else:
                d[strg] = elem
        return d

    def _tolist(ndarray):
        '''
        A recursive function which constructs lists from cellarrays
        (which are loaded as numpy ndarrays), recursing into the elements
        if they contain matobjects.
        '''
        elem_list = []
        for sub_elem in ndarray:
            if isinstance(sub_elem, spio.matlab.mio5_params.mat_struct):
                elem_list.append(_todict(sub_elem))
            elif isinstance(sub_elem, np.ndarray):
                elem_list.append(_tolist(sub_elem))
            else:
                elem_list.append(sub_elem)
        return elem_list
    data = spio.loadmat(filename, struct_as_record=False, squeeze_me=True)
    return _check_keys(data)
```

**Comment by rafabs97** [comment] 2020-11-04 23:34
Are you using exactly the same version for every package as presented in the requirements.txt file?

**Comment by robertodaza** [comment] 2020-11-05 00:43
> I did not create the .mat file, as it is the result of the work developed in another project (https://github.com/AVAuco/ssd_people), and thus I can't provide support for that file, but if you are using exactly the same version of the packages as listed in the requirements.txt file it should work. Are you using a different version of Python or the SciPy package?

No, I am using Python 3.7.6 and SciPy 1.4.1, it is indicated in the file "requirements.txt" and in the field "Software requirements". Is there any way not to use the file .mat ?

**Comment by rafabs97** [comment] 2020-11-05 00:47
I'm going to try to reproduce the error. The .mat file is contains the head detector, and thus it is not needed to use the pose estimator, provided you use another head detection method.

**Comment by rafabs97** [comment] 2020-11-05 01:45
I assume the error appeared when using the "convert_ssd_512.py" script (i think it is the only place in the project where that function is called). I haven't been able to reproduce the error; the script worked as intended generating the "head-detector.h5" file in the "models/" directory. For the reference, I have used Python 3.7.6 (compiled from source: https://linuxize.com/post/how-to-install-python-3-7-on-ubuntu-18-04/), using a clean virtualenv where I installed the packages from the "requirements.txt" file, running on up-to-date Arch Linux x86_64. What OS are you using?

**Comment by robertodaza** [comment] 2020-11-05 09:18
> I assume the error appeared when using the "convert_ssd_512.py" script (i think it is the only place in the project where that function is called). I haven't been able to reproduce the error; the script worked as intended generating the "head-detector.h5" file in the "models/" directory. For the reference, I have used Python 3.7.6 (compiled from source: https://linuxize.com/post/how-to-install-python-3-7-on-ubuntu-18-04/), using a clean virtualenv where I installed the packages from the "requirements.txt" file, running on up-to-date Arch Linux x86_64. What OS are you using?

I am using Windows 10 version 1909 of 64 bits. The error appears when I use the file "convert_ssd_512.py". The error is:

```
  File "/headpose_final-master/convert_ssd_512.py", line 52, in <module>
    model_ori = loadmat(matconvnet_model_path)

  File "\headpose_final-master\loadmat_stackoverflow.py", line 59, in loadmat
    data = spio.loadmat(filename, struct_as_record=False, squeeze_me=True)

  File "\lib\site-packages\scipy\io\matlab\mio.py", line 217, in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)

  File "\lib\site-packages\scipy\io\matlab\mio.py", line 72, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)

  File "\lib\site-packages\scipy\io\matlab\miobase.py", line 241, in get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)

ValueError: Unknown mat file type, version 57, 48
```

**Comment by robertodaza** [comment] 2020-11-05 10:55
I have tried to open the file "head-detector.mat" with matlab 2019 but I always get error `Not a binary MAT-file. Try load -ASCII to read as text`. Also I have  opened the file with notepad and it only contains the next information;

> version https://git-lfs.github.com/spec/v1
> oid sha256:cd5ec15412e5e84259144cf335996be50fcb9d5e4dab82d04412d6895b643807
> size 90941165


The file size is 133 bytes, therefore,  I think the file can be wrong.

I attach the file "head-detector.mat". Could you share the file "head-detector.mat" used in your environment?

[head-detector.zip](https://github.com/rafabs97/headpose_final/files/5493519/head-detector.zip)

**Comment by rafabs97** [comment] 2020-11-05 11:21
I think I know what can be failing. The "head-detector.mat" file is a large file, uploaded using Git LFS: if you try to clone the head detector project (https://github.com/AVAuco/ssd_people) without installing git-lfs it will fail. The authors of that project provide instructions on how to install git-lfs and get the files:

> Install git:     
    `sudo apt-get install git`
Install git-lfs:
    `sudo apt-get install git-lfs`
Set up git-lfs:
    `git lfs install`
Clone ssd_people from GitHub using the method of your choice: 
    `git clone https://github.com/AVAuco/ssd_people.git (HTTPS)`
    `git clone git@github.com:AVAuco/ssd_people.git (SSH)`

**Comment by robertodaza** [comment] 2020-11-05 13:30
> I think I know what can be failing. The "head-detector.mat" file is a large file, uploaded using Git LFS: if you try to clone the head detector project (https://github.com/AVAuco/ssd_people) without installing git-lfs it will fail. The authors of that project provide instructions on how to install git-lfs and get the files:
> 
> > Install git:
> > `sudo apt-get install git`
> > Install git-lfs:
> > `sudo apt-get install git-lfs`
> > Set up git-lfs:
> > `git lfs install`
> > Clone ssd_people from GitHub using the method of your choice:
> > `git clone https://github.com/AVAuco/ssd_people.git (HTTPS)`
> > `git clone git@github.com:AVAuco/ssd_people.git (SSH)`

Thank you very much, it was the problem. One question, will you update to tensorflow 2?

I have modified the code to update to tensorflow 2, but I have errors:

```
Reloaded modules: keras_ssd512, keras_layers, keras_layers.keras_layer_AnchorBoxes, bounding_box_utils, bounding_box_utils.bounding_box_utils, keras_layers.keras_layer_L2Normalization, keras_layers.keras_layer_DecodeDetections, keras_layers.keras_layer_DecodeDetectionsFast, architectures, head_detector_utils, pose_estimator_utils
WARNING:tensorflow:AutoGraph could not transform <bound method L2Normalization.call of <keras_layers.keras_layer_L2Normalization.L2Normalization object at 0x0000020628E88CC8>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
WARNING: AutoGraph could not transform <bound method L2Normalization.call of <keras_layers.keras_layer_L2Normalization.L2Normalization object at 0x0000020628E88CC8>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
WARNING:tensorflow:AutoGraph could not transform <bound method AnchorBoxes.call of <keras_layers.keras_layer_AnchorBoxes.AnchorBoxes object at 0x0000020628EE5E48>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
WARNING: AutoGraph could not transform <bound method AnchorBoxes.call of <keras_layers.keras_layer_AnchorBoxes.AnchorBoxes object at 0x0000020628EE5E48>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
WARNING:tensorflow:AutoGraph could not transform <bound method AnchorBoxes.call of <keras_layers.keras_layer_AnchorBoxes.AnchorBoxes object at 0x0000020628EEA1C8>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
WARNING: AutoGraph could not transform <bound method AnchorBoxes.call of <keras_layers.keras_layer_AnchorBoxes.AnchorBoxes object at 0x0000020628EEA1C8>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
WARNING:tensorflow:AutoGraph could not transform <bound method AnchorBoxes.call of <keras_layers.keras_layer_AnchorBoxes.AnchorBoxes object at 0x0000020628EF5B88>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
WARNING: AutoGraph could not transform <bound method AnchorBoxes.call of <keras_layers.keras_layer_AnchorBoxes.AnchorBoxes object at 0x0000020628EF5B88>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
WARNING:tensorflow:AutoGraph could not transform <bound method AnchorBoxes.call of <keras_layers.keras_layer_AnchorBoxes.AnchorBoxes object at 0x0000020628EFDF08>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
WARNING: AutoGraph could not transform <bound method AnchorBoxes.call of <keras_layers.keras_layer_AnchorBoxes.AnchorBoxes object at 0x0000020628EFDF08>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
WARNING:tensorflow:AutoGraph could not transform <bound method AnchorBoxes.call of <keras_layers.keras_layer_AnchorBoxes.AnchorBoxes object at 0x0000020628F0B308>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
WARNING: AutoGraph could not transform <bound method AnchorBoxes.call of <keras_layers.keras_layer_AnchorBoxes.AnchorBoxes object at 0x0000020628F0B308>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
WARNING:tensorflow:AutoGraph could not transform <bound method AnchorBoxes.call of <keras_layers.keras_layer_AnchorBoxes.AnchorBoxes object at 0x0000020628F08A88>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
WARNING: AutoGraph could not transform <bound method AnchorBoxes.call of <keras_layers.keras_layer_AnchorBoxes.AnchorBoxes object at 0x0000020628F08A88>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
WARNING:tensorflow:AutoGraph could not transform <bound method AnchorBoxes.call of <keras_layers.keras_layer_AnchorBoxes.AnchorBoxes object at 0x0000020628F15048>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
WARNING: AutoGraph could not transform <bound method AnchorBoxes.call of <keras_layers.keras_layer_AnchorBoxes.AnchorBoxes object at 0x0000020628F15048>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
WARNING:tensorflow:AutoGraph could not transform <bound method DecodeDetections.call of <keras_layers.keras_layer_DecodeDetections.DecodeDetections object at 0x0000020628FB8B88>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
WARNING: AutoGraph could not transform <bound method DecodeDetections.call of <keras_layers.keras_layer_DecodeDetections.DecodeDetections object at 0x0000020628FB8B88>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
Traceback (most recent call last):

  File "<ipython-input-3-ffb8ec73e320>", line 1, in <module>
    runfile('C:/Users/rober/Desktop/headpose_final-master/demo_image.py', wdir='C:/Users/rober/Desktop/headpose_final-master')

  File "C:\Users\rober\Anaconda3\envs\Tensorflow_2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\rober\Anaconda3\envs\Tensorflow_2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/rober/Desktop/headpose_final-master/demo_image.py", line 66, in <module>
    bboxes = get_head_bboxes(img, head_detector, confidence_threshold)

  File "C:\Users\rober\Desktop\headpose_final-master\head_detector_utils.py", line 42, in get_head_bboxes
    y_pred = model.predict(input_image)

  File "C:\Users\rober\Anaconda3\envs\Tensorflow_2\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1013, in predict
    use_multiprocessing=use_multiprocessing)

  File "C:\Users\rober\Anaconda3\envs\Tensorflow_2\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 498, in predict
    workers=workers, use_multiprocessing=use_multiprocessing, **kwargs)

  File "C:\Users\rober\Anaconda3\envs\Tensorflow_2\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 475, in _model_iteration
    total_epochs=1)

  File "C:\Users\rober\Anaconda3\envs\Tensorflow_2\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)

  File "C:\Users\rober\Anaconda3\envs\Tensorflow_2\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))

  File "C:\Users\rober\Anaconda3\envs\Tensorflow_2\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)

  File "C:\Users\rober\Anaconda3\envs\Tensorflow_2\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 638, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access

  File "C:\Users\rober\Anaconda3\envs\Tensorflow_2\lib\site-packages\tensorflow_core\python\eager\function.py", line 1611, in _filtered_call
    self.captured_inputs)

  File "C:\Users\rober\Anaconda3\envs\Tensorflow_2\lib\site-packages\tensorflow_core\python\eager\function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))

  File "C:\Users\rober\Anaconda3\envs\Tensorflow_2\lib\site-packages\tensorflow_core\python\eager\function.py", line 545, in call
    ctx=ctx)

  File "C:\Users\rober\Anaconda3\envs\Tensorflow_2\lib\site-packages\tensorflow_core\python\eager\execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)

  File "<string>", line 3, in raise_from

UnknownError: 2 root error(s) found.
  (0) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node model_2/conv1_1/Conv2D (defined at C:\Users\rober\Desktop\headpose_final-master\head_detector_utils.py:42) ]]
	 [[Func/model_2/decoded_predictions/loop_over_batch/while/body/_17/loop_over_classes/while/body/_123/cond/else/_216/input/_231/_70]]
  (1) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node model_2/conv1_1/Conv2D (defined at C:\Users\rober\Desktop\headpose_final-master\head_detector_utils.py:42) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_distributed_function_9792]

Errors may have originated from an input operation.
Input Source operations connected to node model_2/conv1_1/Conv2D:
 model_2/input_channel_swap/stack (defined at C:\Users\rober\Desktop\headpose_final-master\keras_ssd512.py:259)

Input Source operations connected to node model_2/conv1_1/Conv2D:
 model_2/input_channel_swap/stack (defined at C:\Users\rober\Desktop\headpose_final-master\keras_ssd512.py:259)

Function call stack:
distributed_function -> distributed_function
```

**Comment by rafabs97** [comment] 2020-11-05 13:46
Yes, I plan to upgrade the project to Tensorflow 2 and maybe keep improving the estimator model, but I can't give you an estimation on when will it be ready as I don't have much free time right now. However the failure you are getting comes from the implementation of the SSD512 detector used only for demonstration purposes. I didn't code the SSD512 implementation, so I can't provide support for it right now, but as far as I know, the rest of the code works fine on Tensorflow 2, provided you use another head detector.

**Comment by rafabs97** [comment] 2020-11-05 13:53
P.d. I'll close this issue as the original problem was solved. Feel free to contact me for any other issue regarding this project.

**Closed by rafabs97** 2020-11-05 13:53 UTC
